# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3800ce1c41defefe16c91499c9b020c69e01c0b72d7baaaacb6c18a5b18641a7c663e94eb24ac705609a1ec98e535b9715aaf22858fce746380ed206ca36ba7

test:
  secret_key_base: a5a5eada9a1139e6c73458df14f290be5b97965f4e5ea9d168f1717bf9259c3b727ff9b46e8e641641fb57957ece39e89d1bd6ec0967cc0ce040b1fb0942759f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
